/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inf;

import codes.DBconnecter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Ishu & Neth
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
     Connection con = null;
    PreparedStatement pst= null;
    ResultSet rs= null;
    public login() {
        initComponents();
        con = DBconnecter.connect();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginbtn = new javax.swing.JButton();
        signbtn = new javax.swing.JButton();
        unamebox1 = new javax.swing.JTextField();
        passwordbox = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l1.setBackground(new java.awt.Color(255, 255, 255));
        l1.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setText("Login");
        jPanel1.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 80, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 110, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        loginbtn.setBackground(new java.awt.Color(102, 102, 102));
        loginbtn.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        loginbtn.setForeground(new java.awt.Color(255, 255, 255));
        loginbtn.setText("Login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        jPanel1.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        signbtn.setBackground(new java.awt.Color(102, 102, 102));
        signbtn.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        signbtn.setForeground(new java.awt.Color(255, 255, 255));
        signbtn.setText("Signup");
        signbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signbtnActionPerformed(evt);
            }
        });
        jPanel1.add(signbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        unamebox1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(unamebox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 180, -1));

        passwordbox.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(passwordbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 180, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 420, 340));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/h6.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 560));

        setBounds(0, 0, 1297, 602);
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
        String uname;
        String pword;
        
        uname=unamebox1.getText();
        pword=passwordbox.getText();
        try{
          String sql= "SELECT * FROM user WHERE `User Name`=? AND Password=?";
          pst=con.prepareCall(sql);
          pst.setString(1,uname);
          pst.setString(2,pword);
          rs=pst.executeQuery();


            if(uname.equals("")&&pword.equals("")){
                JOptionPane.showMessageDialog(this, "Please enter a username and password."); 
                
            }
            else if(!(uname.equals(""))&&pword.equals("")){
                JOptionPane.showMessageDialog(this, "Please enter a password.");
            }
            else if(uname.equals("")&&!(pword.equals(""))){
                JOptionPane.showMessageDialog(this, "Please enter a username.");
            }
            else if(!rs.next()){
                JOptionPane.showMessageDialog(rootPane, "Your password is incorrect");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Your Login....");
              new mainframe(uname).setVisible(true);
              new login().setVisible(false);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e); 
        }
        
        
       
    }//GEN-LAST:event_loginbtnActionPerformed

    private void signbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signbtnActionPerformed
        // TODO add your handling code here:
        signup s1 = new signup();
       s1.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_signbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPasswordField passwordbox;
    private javax.swing.JButton signbtn;
    private javax.swing.JTextField unamebox1;
    // End of variables declaration//GEN-END:variables
}
