/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inf;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ishu & Neth
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    Connection con = null;
    PreparedStatement pst = null;
    
    public signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        s1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        okbtn = new javax.swing.JButton();
        jcombobox1 = new javax.swing.JComboBox<>();
        sunamebox1 = new javax.swing.JTextField();
        sunamebox2 = new javax.swing.JPasswordField();
        sunamebox = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        s1.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        s1.setForeground(new java.awt.Color(255, 255, 255));
        s1.setText("SignUp");
        jPanel1.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Userlevel");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Confirm Password");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 20));

        okbtn.setBackground(new java.awt.Color(102, 102, 102));
        okbtn.setForeground(new java.awt.Color(255, 255, 255));
        okbtn.setText("OK");
        okbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbtnActionPerformed(evt);
            }
        });
        jPanel1.add(okbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        jcombobox1.setBackground(new java.awt.Color(204, 204, 204));
        jcombobox1.setForeground(new java.awt.Color(255, 255, 255));
        jcombobox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Founder", "Losser" }));
        jcombobox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombobox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jcombobox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 170, -1));

        sunamebox1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(sunamebox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 170, -1));

        sunamebox2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(sunamebox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 170, -1));

        sunamebox.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(sunamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 440, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/h6.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 560));

        setBounds(0, 0, 1297, 602);
    }// </editor-fold>//GEN-END:initComponents

    private void jcombobox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombobox1ActionPerformed
        // TODO add your handling code here:
        String selectedValue= jcombobox1.getSelectedItem().toString();
        
    }//GEN-LAST:event_jcombobox1ActionPerformed

    private void okbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbtnActionPerformed

        try{
            String query = "INSERT INTO `user`(`User Name`,`User Level`,`Password`) VALUES (?,?,?)";
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/findmylostdata", "root", "");
                    pst=con.prepareStatement(query);
                    pst.setString(1, sunamebox1.getText());
                    pst.setString(2, jcombobox1.getSelectedItem().toString());
                    pst.setString(3, sunamebox2.getText());
                    
                    
                    if(sunamebox1.getText().equals("")&&sunamebox2.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "Please fill out user name and password.");
                    }
                    else if(sunamebox2.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "Please fill out password.");
                    }
                    
                    else if(!(new String(sunamebox2.getPassword()).equals(new String(sunamebox.getPassword())))){
                        JOptionPane.showMessageDialog(null, "Your confirm password is not match");
                    }
                    else{
                        pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Register Successfully");
                    login l1=new login();
                    l1.setVisible(true);
                    this.dispose();
                    }
                    
            } catch (Exception ex) {
                    System.out.println(ex);
                }

    }//GEN-LAST:event_okbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcombobox1;
    private javax.swing.JButton okbtn;
    private javax.swing.JLabel s1;
    private javax.swing.JPasswordField sunamebox;
    private javax.swing.JTextField sunamebox1;
    private javax.swing.JPasswordField sunamebox2;
    // End of variables declaration//GEN-END:variables
}
